# Installs core workstation packages
---

- name: Install core workstation packages
  ansible.builtin.dnf:
    name:
      - Zim
      - adobe-source-code-pro-fonts
      - copr-cli
      - fedpkg
      - gh
      - git
      - hplip
      - irssi
      - kiwi-cli
      - mkosi
      - mock
      - python3-pylint
      - ripgrep
      - rubygem-kitchen-ansible
      - rubygem-kitchen-qemu
      - rubygem-kitchen-salt
      - rubygem-test-kitchen
      - s3cmd
      - stow
      - yamllint
      - zsh
